---
version: '2'
services:
  syslog:
    scale: 1
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 514
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 10000
      strategy: recreate
      reinitializing_timeout: 60000
    retain_ip: true
  agent:
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9514
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 10000
      strategy: recreate
      reinitializing_timeout: 60000
  cleanup:
    scale: 1
    start_on_create: true
  monitoring-rules:
    scale: 1
    start_on_create: true
  journald-rate-limit:
    start_on_create: true
